###

POST http://localhost:46019/odata/v2/my/fun_CreateEmployee
Content-Type: application/json

{

  "EMPID": "SLS1037",
  "EMPNM": "Pavan Kumar Angadi",
  "PHONE": 384824851,
  "CITY": "Hyderabad"

}